#include "Pokitto.h"

#include "Number_0.h"
#include "Number_1.h"
#include "Number_2.h"
#include "Number_3.h"
#include "Number_4.h"
#include "Number_5.h"
#include "Number_6.h"
#include "Number_7.h"
#include "Number_8.h"
#include "Number_9.h"
