#include "Pokitto.h"

#include "Key_Rotate_F0.h"
#include "Key_Rotate_F1.h"
#include "Key_Rotate_F2.h"
#include "Key_Rotate_F3.h"
#include "Key_Rotate_F4.h"
#include "Key_Rotate_F5.h"
#include "Key_Rotate_F6.h"
#include "Key_Rotate_F7.h"
#include "Key_Spin_F0.h"
#include "Key_Spin_F1.h"
#include "Key_Spin_F2.h"
#include "Key_Spin_F3.h"
