#include "Pokitto.h"

#include "Jnr_Climbing_Vine_F0.h"
#include "Jnr_Climbing_Vine_F1.h"
#include "Jnr_Idle_L_F0.h"
#include "Jnr_Idle_R_F0.h"
#include "Jnr_OnRope_F0.h"
#include "Jnr_OnRope_F1.h"
#include "Jnr_OnRope_F2.h"
#include "Jnr_OnRope_F3.h"
#include "Jnr_Walking_L_F1.h"
#include "Jnr_Walking_L_F2.h"
#include "Jnr_Walking_R_F1.h"
#include "Jnr_Walking_R_F2.h"
